/*markdown
# Comandos DDL
*/

/*markdown
Criando o esquema `dbex`
*/

CREATE SCHEMA dbex;

/*markdown
## Comando `CREATE TABLE`
*/

/*markdown
Criando a tabela `cidades` usando o tipo `serial` para a coluna `id`
*/

CREATE TABLE IF NOT EXISTS dbex.cidades (
  id serial PRIMARY KEY,
  nome varchar(150) NOT NULL,
  estado char(2) NOT NULL  DEFAULT '--'
);

/*markdown
Criando a tabela `cidades` usando a cláusula `GENERATED ALWAYS` para a coluna `ID`
*/

CREATE TABLE IF NOT EXISTS dbex.cidades (
  id int GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  nome varchar(150) NOT NULL,
  estado char(2) NOT NULL DEFAULT '--'
);

/*markdown
Criando a tabela `cidades` usando a cláusula `GENERATED BY DEFAULT` para a coluna `ID`
*/

CREATE TABLE IF NOT EXISTS dbex.cidades (
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome varchar(150) NOT NULL,
  estado char(2) NOT NULL DEFAULT '--'
);

/*markdown
Criando a tabela `localizacoes`
*/

CREATE TABLE IF NOT EXISTS dbex.localizacoes (
	id int GENERATED ALWAYS AS IDENTITY,
	id_cidade int NOT NULL, 
	latitude float NOT NULL,
	longitude float NOT NULL,
	CONSTRAINT localizacoes_pk PRIMARY KEY (id),
	CONSTRAINT localizacoes_cidades_fk FOREIGN KEY (id_cidade)
				REFERENCES dbex.cidades(id) ON DELETE CASCADE,
	CONSTRAINT localizacoes_un UNIQUE(id_cidade)
);

/*markdown
## Adicionando uma constraint na tabela `localizacoes`
*/

ALTER TABLE dbex.localizacoes ADD CONSTRAINT localizacoes_un2 UNIQUE(latitude, longitude);

/*markdown
Criando a tabela `tempos`
*/


CREATE TABLE IF NOT EXISTS dbex.tempos (
	id int GENERATED ALWAYS AS IDENTITY,
	id_cidade int NOT NULL, 
	temp_min int NOT NULL,
	temp_max int NOT NULL,
	precip_pluviom float NULL DEFAULT '0.0',
	data_coleta TIMESTAMP NOT NULL,
	CONSTRAINT tempos_pk PRIMARY KEY (id),
	CONSTRAINT tempos_cidades_fk FOREIGN KEY (id_cidade)
				REFERENCES dbex.cidades(id) ON DELETE CASCADE
);



/*markdown
Criando a tabela `centrais`
*/

CREATE TABLE IF NOT EXISTS dbex.centrais (
    codigo char(5) NOT NULL,
    CONSTRAINT centrais_pk PRIMARY KEY(codigo)
);

/*markdown
Criando a tabela `centrais_tempos`
*/


CREATE TABLE IF NOT EXISTS dbex.centrais_tempos (
    id_tempo int NOT NULL,
    codigo_central char(5) NOT NULL, 
    CONSTRAINT centrais_tempos_pk PRIMARY KEY (id_tempo, codigo_central),
    CONSTRAINT ct_tempos_fk FOREIGN KEY(id_tempo) REFERENCES dbex.tempos (id),
    CONSTRAINT ct_centrais_fk FOREIGN KEY(codigo_central) REFERENCES dbex.centrais (codigo) ON DELETE CASCADE
);

/*markdown
## Alterando a coluna `codigo` da tabela `centrais`
*/

ALTER TABLE dbex.centrais ALTER COLUMN codigo TYPE char(5);

/*markdown
# Mais sobre os tipos de dados
*/

/*markdown
## Tamanho das Strings
*/

SELECT octet_length('IFRN'::varchar(8));

SELECT octet_length('IFRN Campus Natal-Central'::varchar(8));

SELECT octet_length('IFRN Campus Natal-Central'::text);

SELECT octet_length(''::varchar(8));

SELECT octet_length('IFRN'::char(2));

SELECT octet_length(' '::char(2));

/*markdown
## Comparação com os booleanos
*/

SELECT true='true' as cmp1, true='1' as cmp2, true='on' as cmp3, false='false' as cmp4, false='0' as cmp5, true='off' as cmp6;

/*markdown
## Exemplos de Migrações
*/

/*markdown
### Criando a tabela `clientes`
*/

CREATE TABLE IF NOT EXISTS dbex.clientes (
    id int generated always as identity not null,
    username varchar(150) not null,
    pw_cliente varchar(150) not null,
    constraint clientes_pk primary key(id)
);

DROP TABLE dbex.clientes;

/*markdown
### Alterando o tipo da coluna `pw_cliente`
*/

ALTER TABLE dbex.clientes ALTER COLUMN pw_cliente TYPE int;

/*markdown
## Restrições das _Foreign Keys_
*/

create table if not exists dbex.enderecos (
    id int generated always as identity,
    descricao text not null,
    id_cliente int not null,
    constraint endereco_pk primary key(id),
    constraint endereco_un unique (id_cliente),
    constraint endereco_cliente_fk foreign key(id_cliente) references dbex.clientes(id) on delete no action
);

create table if not exists dbex.enderecos (
    id int generated always as identity,
    descricao text not null,
    id_cliente int not null,
    constraint endereco_pk primary key(id),
    constraint endereco_un unique (id_cliente),
    constraint endereco_cliente_fk foreign key(id_cliente) references dbex.clientes(id) on delete restrict
);

create table if not exists dbex.enderecos (
    id int generated always as identity,
    descricao text not null,
    id_cliente int not null,
    constraint endereco_pk primary key(id),
    constraint endereco_un unique (id_cliente),
    constraint endereco_cliente_fk foreign key(id_cliente) references dbex.clientes(id) on delete cascade
);

create table if not exists dbex.enderecos (
    id int generated always as identity,
    descricao text not null,
    id_cliente int null,
    constraint endereco_pk primary key(id),
    constraint endereco_un unique (id_cliente),
    constraint endereco_cliente_fk foreign key(id_cliente) references dbex.clientes(id) on delete set null
);

create table if not exists dbex.enderecos (
    id int generated always as identity,
    descricao text not null,
    id_cliente int null default 1,
    constraint endereco_pk primary key(id),
    constraint endereco_un unique (id_cliente),
    constraint endereco_cliente_fk foreign key(id_cliente) references dbex.clientes(id) on delete set default
);

drop table dbex.enderecos;

insert into dbex.clientes (username, pw_cliente) values ('fulano de tal','1234');

delete from dbex.clientes where id = 1;

select * from dbex.clientes;

insert into dbex.enderecos (descricao, id_cliente) values ('Av. Sen. Salgado - 1000', 1);

select * from dbex.enderecos;

/*markdown
## Comando `DROP TABLE`
*/

/*markdown
Removendo a tabela `centrais_tempos`
*/

DROP TABLE dbex.centrais_tempos;

/*markdown
Removendo a tabela `centrais`
*/

DROP TABLE dbex.centrais;

/*markdown
Removendo a tabela `tempos`
*/

DROP TABLE dbex.tempos;

/*markdown
Removendo a tabela `localizacoes`
*/

DROP TABLE dbex.localizacoes;

/*markdown
Removendo a tabela `cidades`
*/

DROP TABLE dbex.cidades;