/*markdown
# Comandos DDL
*/

/*markdown
## Criando um esquema
*/

CREATE SCHEMA dbex;

/*markdown
## Criando a tabela `cidades`
*/

/*markdown
### Usando o tipo `serial` para a coluna ´ID´
*/

CREATE TABLE IF NOT EXISTS dbex.cidades (
  id serial PRIMARY KEY,
  nome varchar(150) NOT NULL,
  estado char(2) NOT NULL  DEFAULT '--'
);

/*markdown
### Usando a cláusula `GENERATED ALWAYS' para a coluna ´ID´
*/

CREATE TABLE IF NOT EXISTS dbex.cidades (
  id int GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  nome varchar(150) NOT NULL,
  estado char(2) NOT NULL DEFAULT '--'
);

/*markdown
### Usando a cláusula `GENERATED BY DEFAULT' para a coluna ´ID´
*/

CREATE TABLE IF NOT EXISTS dbex.cidades (
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome varchar(150) NOT NULL,
  estado char(2) NOT NULL DEFAULT '--'
);

/*markdown
## Removendo a tabela `cidades`
*/

DROP TABLE dbex.cidades;

/*markdown
## Criando a tabela `localizacoes`
*/

CREATE TABLE IF NOT EXISTS dbex.localizacoes (
	id int GENERATED ALWAYS AS IDENTITY,
	id_cidade int NOT NULL, 
	latitude float NOT NULL,
	longitude float NOT NULL,
	CONSTRAINT localizacoes_pk PRIMARY KEY (id),
	CONSTRAINT localizacoes_cidades_fk FOREIGN KEY (id_cidade)
				REFERENCES dbex.cidades(id)
);

/*markdown
## Criando a tabela `tempos`
*/

CREATE TABLE IF NOT EXISTS dbex.tempos (
	id int GENERATED ALWAYS AS IDENTITY,
	id_cidade int NOT NULL, 
	temp_min int NOT NULL,
	temp_max int NOT NULL,
	precip_pluviom float NULL DEFAULT '0.0',
	data_coleta TIMESTAMP NOT NULL,
	CONSTRAINT tempos_pk PRIMARY KEY (id),
	CONSTRAINT tempos_cidades_fk FOREIGN KEY (id_cidade)
				REFERENCES dbex.cidades(id)
);

/*markdown
## Criando a tabela `centrais`
*/

CREATE TABLE IF NOT EXISTS dbex.centrais (
    codigo int NOT NULL,
    CONSTRAINT centrais_pk PRIMARY KEY(codigo)
);

/*markdown
## Criando a tabela `centrais_tempos`
*/

CREATE TABLE IF NOT EXISTS dbex.centrais_tempos (
    id_tempo int NOT NULL,
    codigo_central char(5) NOT NULL, 
    CONSTRAINT centrais_tempos_pk PRIMARY KEY (id_tempo, codigo_central),
    CONSTRAINT ct_tempos_fk FOREIGN KEY(id_tempo) REFERENCES dbex.tempos (id),
    CONSTRAINT ct_centrais_fk FOREIGN KEY(codigo_central) REFERENCES dbex.centrais (codigo)
);

/*markdown
# Mais sobre os tipos de dados
*/

/*markdown
## Tamanho das Strings
*/

SELECT octet_length('IFRN'::varchar(8));

SELECT octet_length('IFRN Campus Natal-Central'::varchar(8));


SELECT octet_length('IFRN Campus Natal-Central'::text);

SELECT octet_length(''::varchar(8));

SELECT octet_length('IFRN'::char(2));

SELECT octet_length(' '::char(2));

/*markdown
## Comparação com os booleanos
*/

SELECT true='true' as cmp1, true='1' as cmp2, true='on' as cmp3, false='false' as cmp4, false='0' as cmp5, true='off' as cmp6;